### ISSUE TITLE
com.vaadin.sass.internal.handler.SCSSErrorHandler severe

### ISSUE THREAD

**Issue by Bugi82** [Juchar/product-tour#3]
Hi,
i included dependency into pom but it dost not compile-theme.
I m using dawn (optimised valo theme), then i changed to vaadin-themes (7.7.7) but it does not compile.

SEVERE: null
[ERROR] java.lang.NullPointerException
[ERROR] 	at com.vaadin.sass.internal.util.ColorUtil.adjust(ColorUtil.java:572)
[ERROR] 	at com.vaadin.sass.internal.util.ColorUtil.darken(ColorUtil.java:584)
[ERROR] 	at com.vaadin.sass.internal.parser.function.DarkenFunctionGenerator.computeForArgumentList(DarkenFunctionGenerator.java:42)
[ERROR] 	at com.vaadin.sass.internal.parser.function.AbstractFunctionGenerator.compute(AbstractFunctionGenerator.java:72)
[ERROR] 	at com.vaadin.sass.internal.parser.LexicalUnitImpl.evaluateFunctionsAndExpressions(LexicalUnitImpl.java:826)
[ERROR] 	at com.vaadin.sass.internal.tree.VariableNode.traverse(VariableNode.java:84)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:69)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:67)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] 	at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] 	at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] 	at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] 	at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] 	at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] 	at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] 	at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
[ERROR] 
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: filter not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-panel-caption-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-panel-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: box-shadow not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: filter not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: null
[ERROR] com.vaadin.sass.internal.expression.exception.IncompatibleUnitsException: Incompatible units found in: '$v-unit-size'
[ERROR] 	at com.vaadin.sass.internal.parser.LexicalUnitImpl.checkAndGetUnit(LexicalUnitImpl.java:409)
[ERROR] 	at com.vaadin.sass.internal.parser.LexicalUnitImpl.minus(LexicalUnitImpl.java:392)
[ERROR] 	at com.vaadin.sass.internal.expression.BinaryOperator$10.evalInternal(BinaryOperator.java:144)
[ERROR] 	at com.vaadin.sass.internal.expression.BinaryOperator.eval(BinaryOperator.java:228)
[ERROR] 	at com.vaadin.sass.internal.expression.BinaryExpression.eval(BinaryExpression.java:48)
[ERROR] 	at com.vaadin.sass.internal.expression.ArithmeticExpressionEvaluator.evaluate(ArithmeticExpressionEvaluator.java:116)
[ERROR] 	at com.vaadin.sass.internal.parser.SassExpression.evaluateFunctionsAndExpressions(SassExpression.java:220)
[ERROR] 	at com.vaadin.sass.internal.tree.RuleNode.traverse(RuleNode.java:108)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:69)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:67)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:67)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:67)
[ERROR] 	at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:120)
[ERROR] 	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverse(TemporaryNode.java:71)
[ERROR] 	at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixinNode(MixinNodeHandler.java:75)
[ERROR] 	at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixins(MixinNodeHandler.java:46)
[ERROR] 	at com.vaadin.sass.internal.visitor.MixinNodeHandler.traverse(MixinNodeHandler.java:35)
[ERROR] 	at com.vaadin.sass.internal.tree.MixinNode.traverse(MixinNode.java:116)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] 	at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] 	at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] 	at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] 	at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] 	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] 	at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] 	at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] 	at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
[ERROR] 
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-static-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-borderless-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-borderless-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-quiet-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-borderless-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-link-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: valo-button-style not found
[ERROR] mar. 22, 2017 1:53:22 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: opacity not found
[ERROR] mar. 22, 2017 1:53:23 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SEVERE: Mixin Definition: tour not found

**Comment by Juchar** [comment]
Could you please post the contents of your `styles.scss` file?

---

Do you do any optimization like mentioned in the section [Theme Optimization](https://vaadin.com/docs/-/part/framework/themes/themes-valo.html) inside the book of vaadin?

--- 

Also could you please make sure that you have the correct execution goals for the vaadin-maven-plugin inside of your `pom.xml`:

```
      <plugin>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-maven-plugin</artifactId>
        <version>${vaadin.plugin.version}</version>
        <configuration>
          <style>OBF</style>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>resources</goal>
              <goal>update-widgetset</goal>
              <goal>update-theme</goal>
              <goal>compile-theme</goal>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**Comment by Bugi82** [comment]
Yes, we have pom plugin -> goals
                        <goals>
                            <goal>clean</goal>
                            <goal>resources</goal>
                            <goal>update-widgetset</goal>
                            <goal>update-theme</goal>
                            <goal>compile-theme</goal>
                            <goal>compile</goal>
                        </goals>
AND this is our theme folder. We dont use theme plugin but dawn addon for basic valo theme. We did try including depenency vaadin theme and it still didnt work.

[themes.zip](https://github.com/Juchar/product-tour/files/863787/themes.zip)

**Comment by Juchar** [comment]
Could you please use version `0.2.1`, this should fix the problem.

**Comment by Bugi82** [comment]
Great it compiles now. Will let u know if it works in app. Thank you,

**Comment by Bugi82** [comment]
It works! Thank you. Very usefull addon.
